
# Project information
site_name: Demo site
site_url: 
site_author: me
site_description: >-
  Showcase of dev portal with several resouces

# Repository
repo_name: EDS_documentation
repo_url: https://github.com/vincentlel/

# Copyright
copyright: Copyright &copy; 2025 EarthDaily

# Theme
theme:
  name: material
  features:
    - content.action.edit
    - content.action.view
    - content.tooltips
    - navigation.sections
#  icon:
#    logo: logo

# Plugins
#plugins:
 # - projects:
  #    projects_dir: docs
#      projects_config_transform: !!python/name:examples.transform
   #   log_level: info
 # - render_swagger

# Hooks
# hooks:
#  - hooks/archive.py

validation:
  nav:
    omitted_files: warn
    not_found: warn
    absolute_links: warn
  links:
    not_found: warn
    absolute_links: warn
    unrecognized_links: warn

# Customization
extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - toc:
      permalink: true
#  - pymdownx.betterem:
#     smart_enable: all
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.keys
#  - pymdownx.tabbed:
#      alternate_style: truetest
# Navigation

nav:
  - Home: API Authentication.md
  - About: WelcomeEmail.md
